### ISSUE TITLE
Please upgrade to null-safety version

### ISSUE THREAD

**Issue by diepvicuong** [hurshi/dio-http-cache#97]

**Comment by nitishk72** [comment]
Its' already migrated 
just need to publish

**Comment by amanokerim** [comment]
Thanks to your package my app is fast as 🚀
Thank you!!!

**Comment by PAMAZ** [comment]
@nitishk72 Do you have any updates for us?

**Comment by shinlh** [comment]
@nitishk72 any updates? I need this to migrate my app to Flutter 2.2.1

**Comment by tbm98** [comment]
@shinlh just fork it and point to your git repo

**Comment by mahidul-islam** [comment]
Is there a technical problem with publishing it?

**Comment by marcodafonseca** [comment]
We have temporarily gotten around this problem by adding the following to our pubspec.yaml:

```
dio_http_cache:
    git:
      url: https://github.com/vrtdev/dio-http-cache.git
      ref: feature/nullsafety-dio4
```
      
This obviously isn't ideal. When will an official null-safe version be released?
